// One source of truth for names retired by the domain-vocabulary rebuild.
// Both source and built-declaration guards consume exact tokens from this list;
// patterns would accidentally reject valid names such as PluginContext.
export const retiredVocabulary = Object.freeze([
  // Host and its former internal collaborators.
  "Application",
  "ApplicationDiagnostics",
  "ApplicationImpl",
  "ApplicationRuntime",
  "ApplicationRuntimeOptions",
  "ApplicationSnapshot",
  "ApplicationStatus",
  "CreateAppOptions",
  "RuntimeChangeOutcome",
  "createApp",
  // Former callback-protocol suffixes now expressed as Ports.
  "GroupCoordinatorHost",
  "LifetimeHost",
  "PlatformChangeHost",
  "PluginChangeHost",
  // Core installation and contribution vocabulary.
  "Extension",
  "ExtensionLeaseKind",
  "ExtensionRegistry",
  "ExtensionRequirementView",
  "ExtensionStore",
  "ExtensionView",
  "GroupHandleControl",
  "GroupStatus",
  "InstallationHandle",
  "InstallationStatus",
  "PluginChangeSet",
  "PluginContainer",
  "PluginDefinition",
  "PluginGraph",
  "PluginGroup",
  "PluginGroupImpl",
  "PluginGroupState",
  "PluginHandle",
  "PluginMeta",
  "PluginSnapshot",
  "PluginUpdate",
  "discardPluginChangeSetDraft",
  "extension",
  // Platform stages formerly collapsed under the Plugin prefix.
  "CreatePlatformOptions",
  "ImportPluginLoader",
  "ManagedPlugin",
  "ManagedPluginSnapshot",
  "ManagedPluginStatus",
  "MemoryPluginLoader",
  "PermissionAuthorizer",
  "PluginArtifact",
  "PluginLoader",
  "PluginManifest",
  "PluginManifestInput",
  "PluginPlatform",
  "PluginPlatformSnapshot",
  "PluginPlatformStatus",
  "loadPluginDefinition",
  // Error codes renamed around the stable Registration identity.
  "PLUGIN_CYCLE",
  "PLUGIN_DEPENDENCY_INACTIVE",
  "PLUGIN_DEPENDENCY_INCOMPATIBLE",
  "PLUGIN_DEPENDENCY_MISSING",
  "PLUGIN_DUPLICATE",
]);
